development:
  db: 0
  host: localhost
  port: 6379
  namespace: chatham
test:
  db: 1
  host: localhost
  port: 6379
  namespace: chatham
staging:
  db: 0
  host: localhost
  port: 6379
  namespace: chatham
production:
  db: 0
  host: ip-10-91-3-30.ec2.internal
  port: 6379
  namespace: chatham
